import pandas as pd
import os
from datetime import datetime

class InteractionLogger:
    def __init__(self, log_file="src/logger/logs.csv"):
        self.log_file = log_file

    def log_interaction(self, query, response):
        """
        Logs the user query and LLM response into a CSV file.

        Args:
            query (str): The user's query.
            response (str): The response generated by the LLM.
        """
        log_entry = pd.DataFrame([{
            "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "User Query": query,
            "LLM Response": response
        }])

        if os.path.isfile(self.log_file):
            # Read existing CSV and append new data
            df = pd.read_csv(self.log_file)
            df = pd.concat([df, log_entry], ignore_index=True)
        else:
            # Create new CSV file if it doesn't exist
            df = log_entry

        # Save the updated DataFrame to CSV
        df.to_csv(self.log_file, index=False)
        print(f"Interaction logged successfully in '{self.log_file}'.")
def main():
    test = InteractionLogger()
    test.log_interaction("sss","jjjjj")

if __name__ == "__main__":
    main()